version: "3"
services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/dev-disk-by-uuid-e402302d-7f58-428d-8959-4d9dffa08ddb/config:/config
      - ./plugins:/plugins
      - ./scripts:/config/custom-cont-init.d
      - /srv/dev-disk-by-uuid-e402302d-7f58-428d-8959-4d9dffa08ddb/audiobooks/audiobooks:/audiobooks
      - /srv/dev-disk-by-uuid-e402302d-7f58-428d-8959-4d9dffa08ddb/audiobooks/temp/untagged:/untagged
    restart: unless-stopped
